### ISSUE TITLE
linker error on macos 10.14, postgres.app 2.25

### ISSUE THREAD

**Issue by daboe01** [guenthermi/postgres-word2vec#15]
sudo make install gives:
Undefined symbols for architecture x86_64:
  "_addToTargetList", referenced from:
      _ivpq_search_in in ivpq_search_in.o
  "_computePQDistanceInt16", referenced from:
      _pq_search_in_batch in freddy.o
      _ivpq_search_in in ivpq_search_in.o
  "_initTargetLists", referenced from:
      _ivpq_search_in in ivpq_search_in.o
  "_reorderTopKPV", referenced from:
      _ivpq_search_in in ivpq_search_in.o
  "_updateTopKPVFast", referenced from:
      _ivpq_search_in in ivpq_search_in.o
ld: symbol(s) not found for architecture x86_64

i can get around most of them by removing the 'inline'.

however, the addToTargetList function seems to be missing.
any ideas

https://github.com/guenthermi/postgres-word2vec/blob/5e469aa59d0f322980ae37683d390b0457119300/freddy_extension/ivpq_search_in.c#L479

**Comment by guenthermi** [comment]
Sorry, I didn't test the code on mac os. The use of the inline should be fixed somewhen. I think the error did not occur on Linux because of the -O2 flag which is added by pg_config in the makefile.  The addToTargetList function is present in the `postgres-word2vec/freddy_extension/index_utils.h` file. Maybe it helps to remove the inline there. Otherwise, you can also try to replace the inlines with `static inline`.

**Comment by daboe01** [comment]
thank you! removing the static did the trick!
